import { PrismaClient } from "../src/generated/prisma/client";
import { PrismaPg } from "@prisma/adapter-pg";
import { Pool } from "pg";
import { hash } from "bcryptjs";

const pool = new Pool({
  connectionString:
    process.env.DATABASE_URL ||
    "postgresql://kwonrishop:kwonrishop_dev@localhost:5432/yeosialba?schema=public",
});
const adapter = new PrismaPg(pool);
const prisma = new PrismaClient({ adapter });

const SAMPLE_ADS = [
  // 1. BANNER
  {
    title: "강남 프리미엄 룸싸롱 대규모 채용",
    businessName: "강남 다이아몬드",
    businessType: "ROOM_SALON" as const,
    regions: ["SEOUL" as const],
    salaryText: "일급 50만~80만+α",
    workHours: "PM 7:00 ~ AM 3:00",
    benefits: "의상, 헤어, 메이크업, 숙소, 택시비 전부 지원",
    description: "강남 최고급 프리미엄 룸싸롱에서 대규모 채용합니다.\n\n업계 최고 대우, 경력 무관.\n숙소 완비, 전국에서 오시는 분 환영!",
    contactPhone: "01011112222",
    contactKakao: "diamond_ceo",
    thumbnailUrl: null,
  },
  // 2. VIP 1
  {
    title: "강남 고급 룸싸롱 여성 정직원 모집",
    businessName: "강남 로얄클럽",
    businessType: "ROOM_SALON" as const,
    regions: ["SEOUL" as const],
    salaryText: "일급 30만~50만+α",
    workHours: "PM 7:00 ~ AM 3:00",
    benefits: "의상 제공, 식사 제공, 택시비 지원, 숙소 제공 가능",
    description: "강남 최고급 룸싸롱에서 함께할 분을 모집합니다.\n\n경력 무관, 미경험자도 환영합니다.",
    contactPhone: "01012345678",
    contactKakao: "royalclub_ceo",
  },
  // 3. VIP 2
  {
    title: "청담 하이엔드 바라운지 채용",
    businessName: "청담 루미에르",
    businessType: "BAR_LOUNGE" as const,
    regions: ["SEOUL" as const],
    salaryText: "일급 40만~60만",
    workHours: "PM 8:00 ~ AM 4:00",
    benefits: "숙소, 의상, 택시비, 식사 제공",
    description: "청담동 최고급 바라운지에서 함께할 분을 찾습니다.\n\n고급스러운 분위기에서 일하고 싶으신 분 환영!",
    contactPhone: "01011223344",
    contactKakao: "lumiere_cd",
  },
  // 4. PREMIUM 1
  {
    title: "홍대 텐카페 신규 오픈 대량 모집",
    businessName: "홍대 스타카페",
    businessType: "TEN_CAFE" as const,
    regions: ["SEOUL" as const],
    salaryText: "시급 25,000~35,000",
    workHours: "PM 6:00 ~ AM 2:00",
    benefits: "식사 제공, 의상 제공",
    description: "홍대에 신규 오픈하는 텐카페입니다!\n\n밝고 활기찬 분위기에서 함께할 분을 모집합니다.",
    contactPhone: "01023456789",
    contactKakao: "starcafe_hd",
  },
  // 5. PREMIUM 2
  {
    title: "분당 프리미엄 셔츠룸 정직원",
    businessName: "분당 엘리시움",
    businessType: "SHIRT_ROOM" as const,
    regions: ["GYEONGGI" as const],
    salaryText: "일급 35만~50만",
    workHours: "PM 7:30 ~ AM 3:00",
    benefits: "셔츠 제공, 식사, 택시비",
    description: "분당 최대 규모 셔츠룸에서 정직원을 구합니다.\n\n안정적인 수입 보장!",
    contactPhone: "01033445566",
    contactKakao: "elysium_bd",
  },
  // 6. SPECIAL 1
  {
    title: "부산 서면 바라운지 스탭 모집",
    businessName: "서면 블루라운지",
    businessType: "BAR_LOUNGE" as const,
    regions: ["BUSAN" as const],
    salaryText: "시급 20,000~30,000",
    workHours: "PM 8:00 ~ AM 4:00",
    benefits: "식사 제공, 택시비 지원",
    description: "서면 중심가에 위치한 바라운지에서 스탭을 구합니다.",
    contactPhone: "01034567890",
  },
  // 7. SPECIAL 2
  {
    title: "해운대 클럽 주말 파트 모집",
    businessName: "해운대 웨이브",
    businessType: "CLUB" as const,
    regions: ["BUSAN" as const],
    salaryText: "시급 35,000+팁",
    workHours: "PM 10:00 ~ AM 5:00 (금토)",
    benefits: "팁 전액, 음료 무제한",
    description: "해운대 최대 클럽에서 주말 파트타임을 구합니다.\n\n팁 전액 본인!",
    contactPhone: "01044556677",
  },
  // 8. URGENT 1
  {
    title: "강남 퍼블릭바 주말 파트타임 급구",
    businessName: "강남 네온바",
    businessType: "PUBLIC_BAR" as const,
    regions: ["SEOUL" as const, "GYEONGGI" as const],
    salaryText: "시급 22,000+팁",
    workHours: "PM 9:00 ~ AM 5:00 (주말)",
    benefits: "팁 100% 본인, 식사 제공",
    description: "강남역 5분 거리 퍼블릭바에서 주말 파트타임을 구합니다.\n\n팁 전액 본인!\n바로 출근 가능한 분 연락주세요.",
    contactPhone: "01045678901",
    contactKakao: "neonbar",
  },
  // 9. URGENT 2
  {
    title: "경기 수원 셔츠룸 긴급 채용",
    businessName: "수원 엘리트",
    businessType: "SHIRT_ROOM" as const,
    regions: ["GYEONGGI" as const],
    salaryText: "일급 28만~45만",
    workHours: "PM 7:30 ~ AM 3:00",
    benefits: "식사, 셔츠 제공, 택시비",
    description: "수원 인계동 셔츠룸에서 급하게 채용합니다.\n\n바로 출근 가능한 분 우대!\n일급 당일 정산.",
    contactPhone: "01078901234",
  },
  // 10. RECOMMEND 1
  {
    title: "대구 동성로 노래방 도우미 모집",
    businessName: "동성로 스타노래방",
    businessType: "KARAOKE" as const,
    regions: ["DAEGU" as const],
    salaryText: "일급 15만~25만",
    workHours: "PM 7:00 ~ AM 2:00",
    benefits: "식사, 의상 제공",
    description: "대구 동성로 대형 노래방에서 도우미를 모집합니다.",
    contactPhone: "01056789012",
  },
  // 11. RECOMMEND 2
  {
    title: "인천 하이퍼블릭 정직원 구합니다",
    businessName: "인천 파티클럽",
    businessType: "HYPER_PUBLIC" as const,
    regions: ["INCHEON" as const],
    salaryText: "일급 25만~40만",
    workHours: "PM 8:00 ~ AM 4:00",
    benefits: "숙소, 식사, 의상, 택시비 전부 제공",
    description: "인천 최대 규모 하이퍼블릭에서 정직원을 구합니다.",
    contactPhone: "01067890123",
    contactKakao: "partyclub_ic",
  },
  // 12. LINE 1
  {
    title: "광주 클럽 주말 알바 모집",
    businessName: "광주 매직클럽",
    businessType: "CLUB" as const,
    regions: ["GWANGJU" as const],
    salaryText: "시급 30,000+팁",
    workHours: "PM 10:00 ~ AM 5:00 (금토)",
    benefits: "팁 전액, 음료 무제한",
    description: "광주 최대 클럽에서 주말 파트타임을 구합니다.",
    contactPhone: "01089012345",
  },
  // 13. LINE 2
  {
    title: "대전 마사지샵 관리사 모집",
    businessName: "대전 힐링스파",
    businessType: "MASSAGE" as const,
    regions: ["DAEJEON" as const],
    salaryText: "월급 250만~350만",
    workHours: "AM 11:00 ~ PM 10:00 (교대)",
    benefits: "숙소 제공, 식사 제공",
    description: "대전 중심가 마사지샵에서 관리사를 모집합니다.\n\n경력자 우대.",
    contactPhone: "01090123456",
  },
  // 14. LINE 3
  {
    title: "울산 노래방 파트타임",
    businessName: "울산 스타노래방",
    businessType: "KARAOKE" as const,
    regions: ["ULSAN" as const],
    salaryText: "시급 18,000~25,000",
    workHours: "PM 8:00 ~ AM 2:00",
    benefits: "식사 제공",
    description: "울산 중구 노래방에서 파트타임을 구합니다.",
    contactPhone: "01001234567",
  },
  // 15. LINE 4
  {
    title: "제주 바라운지 스탭 채용",
    businessName: "제주 선셋바",
    businessType: "BAR_LOUNGE" as const,
    regions: ["JEJU" as const],
    salaryText: "시급 20,000~28,000",
    workHours: "PM 7:00 ~ AM 3:00",
    benefits: "숙소 제공, 식사 제공, 항공권 지원",
    description: "제주도 바라운지에서 스탭을 채용합니다.\n\n숙소+항공권 지원!",
    contactPhone: "01012340000",
    contactKakao: "sunset_jeju",
  },
  // 16. FREE 1
  {
    title: "강릉 카페 아르바이트 모집",
    businessName: "강릉 바다카페",
    businessType: "TEN_CAFE" as const,
    regions: ["GANGWON" as const],
    salaryText: "시급 15,000",
    workHours: "PM 2:00 ~ PM 10:00",
    benefits: "식사 제공",
    description: "강릉 해변가 카페에서 아르바이트를 구합니다.\n\n편안한 분위기에서 일하실 분 연락주세요.",
    contactPhone: "01055556666",
  },
  // 17. FREE 2
  {
    title: "춘천 노래방 도우미 모집",
    businessName: "춘천 뮤직노래방",
    businessType: "KARAOKE" as const,
    regions: ["GANGWON" as const],
    salaryText: "일급 12만~18만",
    workHours: "PM 8:00 ~ AM 2:00",
    benefits: "식사 제공",
    description: "춘천 중심가 노래방에서 도우미를 구합니다.",
    contactPhone: "01066667777",
  },
  // 18. FREE 3
  {
    title: "전주 술집 홀 서빙 모집",
    businessName: "전주 전통주점",
    businessType: "PUBLIC_BAR" as const,
    regions: ["JEONBUK" as const],
    salaryText: "시급 12,000",
    workHours: "PM 6:00 ~ AM 1:00",
    description: "전주 한옥마을 인근 전통주점에서 홀 서빙을 구합니다.\n\n한복 제공, 관광객 많은 곳입니다.",
    contactPhone: "01077778888",
  },
  // 19-28. BANNER (10개)
  {
    title: "압구정 최고급 룸싸롱 대규모 채용",
    businessName: "압구정 플래티넘",
    businessType: "ROOM_SALON" as const,
    regions: ["SEOUL" as const],
    salaryText: "일급 60만~100만+α",
    workHours: "PM 7:00 ~ AM 4:00",
    benefits: "의상, 헤어, 메이크업, 숙소, 식비, 택시비 전액 지원",
    description: "압구정 최고급 프리미엄 룸싸롱에서 대규모 채용합니다.\n\n업계 최고 대우, 경력 무관. 숙소 완비, 전국에서 오시는 분 환영!",
    contactPhone: "01098761234",
    contactKakao: "platinum_ceo",
    thumbnailUrl: null,
  },
  {
    title: "청담 VIP 룸싸롱 여성 정직원 급구",
    businessName: "청담 임페리얼",
    businessType: "ROOM_SALON" as const,
    regions: ["SEOUL" as const],
    salaryText: "일급 55만~90만+α",
    workHours: "PM 7:30 ~ AM 3:30",
    benefits: "전 의상 제공, 프리미엄 숙소, 고급 식사, 택시비, 헤어/메이크업",
    description: "청담동 VIP 전용 룸싸롱입니다.\n\n최상급 대우와 안전한 근무환경을 약속드립니다.",
    contactPhone: "01087652341",
    contactKakao: "imperial_cd",
    thumbnailUrl: null,
  },
  {
    title: "강남역 하이퍼블릭 신규 오픈 채용",
    businessName: "강남 골든펄",
    businessType: "HYPER_PUBLIC" as const,
    regions: ["SEOUL" as const],
    salaryText: "일급 45만~75만+팁",
    workHours: "PM 8:00 ~ AM 5:00",
    benefits: "의상, 숙소, 식사, 택시비 전부 제공, 팁 100% 본인",
    description: "강남역 도보 3분! 신규 오픈 하이퍼블릭에서 함께할 분을 찾습니다.\n\n깔끔한 시설, 최고의 대우!",
    contactPhone: "01076543219",
    thumbnailUrl: null,
  },
  {
    title: "분당 럭셔리 바라운지 대규모 모집",
    businessName: "분당 샹젤리제",
    businessType: "BAR_LOUNGE" as const,
    regions: ["GYEONGGI" as const],
    salaryText: "일급 50만~80만",
    workHours: "PM 8:00 ~ AM 4:00",
    benefits: "숙소, 의상, 식사, 택시비, 인센티브",
    description: "분당 최대 규모 럭셔리 바라운지입니다.\n\n편안한 분위기에서 고소득을 원하시는 분 환영!",
    contactPhone: "01065432187",
    contactKakao: "champs_bd",
    thumbnailUrl: null,
  },
  {
    title: "판교 프리미엄 셔츠룸 정직원 대량 채용",
    businessName: "판교 크라운",
    businessType: "SHIRT_ROOM" as const,
    regions: ["GYEONGGI" as const],
    salaryText: "일급 40만~70만",
    workHours: "PM 7:00 ~ AM 3:00",
    benefits: "셔츠 제공, 숙소, 식사, 택시비, 인센티브",
    description: "판교 테크노밸리 인근 프리미엄 셔츠룸입니다.\n\n안정적인 수입과 체계적인 관리!",
    contactPhone: "01054321876",
    thumbnailUrl: null,
  },
  {
    title: "서면 최고급 룸싸롱 대규모 채용",
    businessName: "부산 로얄팰리스",
    businessType: "ROOM_SALON" as const,
    regions: ["BUSAN" as const],
    salaryText: "일급 50만~85만+α",
    workHours: "PM 7:00 ~ AM 3:30",
    benefits: "의상, 숙소, 식사, 택시비 전액 지원",
    description: "부산 서면 최고급 룸싸롱에서 대규모 채용합니다.\n\n부산 최고 대우, 경력 무관!",
    contactPhone: "01043218765",
    contactKakao: "palace_busan",
    thumbnailUrl: null,
  },
  {
    title: "해운대 럭셔리 클럽 정직원 모집",
    businessName: "해운대 프리즘",
    businessType: "CLUB" as const,
    regions: ["BUSAN" as const],
    salaryText: "일급 45만~70만+팁",
    workHours: "PM 10:00 ~ AM 6:00",
    benefits: "의상, 숙소, 식사, 팁 전액 본인",
    description: "해운대 최대 규모 럭셔리 클럽입니다.\n\n높은 팁과 안정적인 수입 보장!",
    contactPhone: "01032187654",
    contactKakao: "prism_haeundae",
    thumbnailUrl: null,
  },
  {
    title: "대구 동성로 프리미엄 바라운지 채용",
    businessName: "대구 에메랄드",
    businessType: "BAR_LOUNGE" as const,
    regions: ["DAEGU" as const],
    salaryText: "일급 40만~65만",
    workHours: "PM 8:00 ~ AM 4:00",
    benefits: "숙소, 의상, 식사, 택시비 전부 지원",
    description: "대구 동성로 중심가 프리미엄 바라운지입니다.\n\n최고의 시설과 대우를 약속드립니다!",
    contactPhone: "01021876543",
    thumbnailUrl: null,
  },
  {
    title: "대전 둔산 고급 룸싸롱 정직원 모집",
    businessName: "대전 골드타워",
    businessType: "ROOM_SALON" as const,
    regions: ["DAEJEON" as const],
    salaryText: "일급 45만~75만+α",
    workHours: "PM 7:30 ~ AM 3:30",
    benefits: "의상, 헤어, 메이크업, 숙소, 식사, 택시비",
    description: "대전 둔산 최고급 룸싸롱에서 정직원을 모집합니다.\n\n대전 최고 수입 보장!",
    contactPhone: "01010987654",
    contactKakao: "goldtower_dj",
    thumbnailUrl: null,
  },
  {
    title: "광주 상무지구 프리미엄 하이퍼블릭 채용",
    businessName: "광주 프레스티지",
    businessType: "HYPER_PUBLIC" as const,
    regions: ["GWANGJU" as const],
    salaryText: "일급 40만~70만+팁",
    workHours: "PM 8:00 ~ AM 5:00",
    benefits: "의상, 숙소, 식사, 택시비, 팁 100%",
    description: "광주 상무지구 프리미엄 하이퍼블릭입니다.\n\n광주 최고 시설과 대우!",
    contactPhone: "01019876543",
    thumbnailUrl: null,
  },
  // 29-38. VIP (10개)
  {
    title: "역삼 고급 룸싸롱 채용",
    businessName: "역삼 루비클럽",
    businessType: "ROOM_SALON" as const,
    regions: ["SEOUL" as const],
    salaryText: "일급 35만~55만+α",
    workHours: "PM 7:00 ~ AM 3:00",
    benefits: "의상, 식사, 택시비, 숙소 제공 가능",
    description: "역삼동 중심가 고급 룸싸롱입니다.\n\n경력 무관, 밝고 성실하신 분 환영!",
    contactPhone: "01098765432",
    contactKakao: "ruby_ys",
    thumbnailUrl: null,
  },
  {
    title: "논현 프리미엄 바라운지 정직원",
    businessName: "논현 오션뷰",
    businessType: "BAR_LOUNGE" as const,
    regions: ["SEOUL" as const],
    salaryText: "일급 38만~58만",
    workHours: "PM 8:00 ~ AM 4:00",
    benefits: "숙소, 의상, 식사, 택시비",
    description: "논현동 프리미엄 바라운지에서 함께할 분을 찾습니다.\n\n세련된 분위기, 좋은 대우!",
    contactPhone: "01087654321",
    contactKakao: "ocean_nh",
    thumbnailUrl: null,
  },
  {
    title: "선릉 하이퍼블릭 정직원 모집",
    businessName: "선릉 파라다이스",
    businessType: "HYPER_PUBLIC" as const,
    regions: ["SEOUL" as const],
    salaryText: "일급 32만~52만+팁",
    workHours: "PM 8:00 ~ AM 5:00",
    benefits: "의상, 숙소, 식사, 택시비, 팁 전액",
    description: "선릉역 도보 5분 하이퍼블릭입니다.\n\n편안한 근무환경과 좋은 동료들!",
    contactPhone: "01076543210",
    thumbnailUrl: null,
  },
  {
    title: "수원 영통 고급 셔츠룸 채용",
    businessName: "영통 사파이어",
    businessType: "SHIRT_ROOM" as const,
    regions: ["GYEONGGI" as const],
    salaryText: "일급 33만~53만",
    workHours: "PM 7:30 ~ AM 3:00",
    benefits: "셔츠 제공, 식사, 택시비, 숙소 가능",
    description: "수원 영통 대형 셔츠룸에서 정직원을 구합니다.\n\n안정적인 수입과 체계적인 관리!",
    contactPhone: "01065432109",
    contactKakao: "sapphire_yt",
    thumbnailUrl: null,
  },
  {
    title: "일산 킨텍스 프리미엄 바라운지",
    businessName: "일산 크리스탈",
    businessType: "BAR_LOUNGE" as const,
    regions: ["GYEONGGI" as const],
    salaryText: "일급 35만~55만",
    workHours: "PM 8:00 ~ AM 4:00",
    benefits: "숙소, 의상, 식사, 택시비",
    description: "일산 킨텍스 인근 프리미엄 바라운지입니다.\n\n쾌적한 환경에서 일하실 분!",
    contactPhone: "01054321098",
    thumbnailUrl: null,
  },
  {
    title: "해운대 고급 룸싸롱 정직원",
    businessName: "해운대 썬플라워",
    businessType: "ROOM_SALON" as const,
    regions: ["BUSAN" as const],
    salaryText: "일급 34만~54만+α",
    workHours: "PM 7:00 ~ AM 3:00",
    benefits: "의상, 숙소, 식사, 택시비",
    description: "해운대 해변 인근 고급 룸싸롱입니다.\n\n부산 최고의 근무환경!",
    contactPhone: "01043210987",
    contactKakao: "sunflower_hd",
    thumbnailUrl: null,
  },
  {
    title: "대구 수성 럭셔리 바라운지",
    businessName: "수성 라벤더",
    businessType: "BAR_LOUNGE" as const,
    regions: ["DAEGU" as const],
    salaryText: "일급 33만~53만",
    workHours: "PM 8:00 ~ AM 4:00",
    benefits: "숙소, 의상, 식사, 택시비",
    description: "대구 수성구 럭셔리 바라운지에서 정직원을 모집합니다.\n\n좋은 근무조건과 분위기!",
    contactPhone: "01032109876",
    thumbnailUrl: null,
  },
  {
    title: "대전 유성 프리미엄 하이퍼블릭",
    businessName: "유성 스카이라운지",
    businessType: "HYPER_PUBLIC" as const,
    regions: ["DAEJEON" as const],
    salaryText: "일급 31만~51만+팁",
    workHours: "PM 8:00 ~ AM 5:00",
    benefits: "의상, 숙소, 식사, 택시비, 팁 전액",
    description: "대전 유성 온천 인근 프리미엄 하이퍼블릭입니다.\n\n쾌적한 시설과 좋은 대우!",
    contactPhone: "01021098765",
    contactKakao: "sky_ys",
    thumbnailUrl: null,
  },
  {
    title: "인천 송도 고급 바라운지 채용",
    businessName: "송도 오션스타",
    businessType: "BAR_LOUNGE" as const,
    regions: ["INCHEON" as const],
    salaryText: "일급 36만~56만",
    workHours: "PM 8:00 ~ AM 4:00",
    benefits: "숙소, 의상, 식사, 택시비",
    description: "인천 송도 신도시 고급 바라운지입니다.\n\n깨끗한 시설과 좋은 근무환경!",
    contactPhone: "01010987654",
    thumbnailUrl: null,
  },
  {
    title: "울산 삼산 프리미엄 셔츠룸",
    businessName: "삼산 문스톤",
    businessType: "SHIRT_ROOM" as const,
    regions: ["ULSAN" as const],
    salaryText: "일급 32만~52만",
    workHours: "PM 7:30 ~ AM 3:00",
    benefits: "셔츠 제공, 식사, 택시비, 숙소 가능",
    description: "울산 삼산동 프리미엄 셔츠룸입니다.\n\n안정적인 수입 보장!",
    contactPhone: "01019876543",
    contactKakao: "moonstone_us",
    thumbnailUrl: null,
  },
  // 39-48. PREMIUM (10개)
  {
    title: "강남 텐카페 정직원 모집",
    businessName: "강남 스위트카페",
    businessType: "TEN_CAFE" as const,
    regions: ["SEOUL" as const],
    salaryText: "시급 28,000~38,000",
    workHours: "PM 6:00 ~ AM 2:00",
    benefits: "식사 제공, 의상 제공, 택시비",
    description: "강남역 인근 텐카페에서 정직원을 모집합니다.\n\n밝은 분위기에서 함께 일하실 분!",
    contactPhone: "01098765431",
    contactKakao: "sweet_gn",
    thumbnailUrl: null,
  },
  {
    title: "신촌 레깅스룸 스탭 채용",
    businessName: "신촌 퍼펙트",
    businessType: "LEGGINGS_ROOM" as const,
    regions: ["SEOUL" as const],
    salaryText: "일급 30만~45만",
    workHours: "PM 7:00 ~ AM 3:00",
    benefits: "레깅스 제공, 식사, 택시비",
    description: "신촌 중심가 레깅스룸입니다.\n\n깔끔한 시설, 좋은 근무환경!",
    contactPhone: "01087654320",
    thumbnailUrl: null,
  },
  {
    title: "건대 셔츠룸 정직원 모집",
    businessName: "건대 썬더",
    businessType: "SHIRT_ROOM" as const,
    regions: ["SEOUL" as const],
    salaryText: "일급 32만~47만",
    workHours: "PM 7:30 ~ AM 3:00",
    benefits: "셔츠 제공, 식사, 택시비",
    description: "건대입구역 도보 3분 셔츠룸입니다.\n\n대학가 활기찬 분위기!",
    contactPhone: "01076543219",
    contactKakao: "thunder_gd",
    thumbnailUrl: null,
  },
  {
    title: "수원역 퍼블릭바 스탭 채용",
    businessName: "수원 나이트스카이",
    businessType: "PUBLIC_BAR" as const,
    regions: ["GYEONGGI" as const],
    salaryText: "시급 25,000~35,000+팁",
    workHours: "PM 9:00 ~ AM 5:00",
    benefits: "식사 제공, 팁 전액 본인",
    description: "수원역 앞 퍼블릭바에서 스탭을 모집합니다.\n\n팁 좋은 곳입니다!",
    contactPhone: "01065432198",
    thumbnailUrl: null,
  },
  {
    title: "안양 관리실 정직원 모집",
    businessName: "안양 스파에덴",
    businessType: "GUANRI" as const,
    regions: ["GYEONGGI" as const],
    salaryText: "월급 280만~380만",
    workHours: "AM 11:00 ~ PM 10:00 (교대)",
    benefits: "숙소 제공, 식사 제공, 4대보험",
    description: "안양 중심가 관리실에서 관리사를 모집합니다.\n\n경력자 우대, 신입도 환영!",
    contactPhone: "01054321987",
    contactKakao: "eden_ay",
    thumbnailUrl: null,
  },
  {
    title: "부산 남포 텐카페 채용",
    businessName: "남포 스타벅스(텐)",
    businessType: "TEN_CAFE" as const,
    regions: ["BUSAN" as const],
    salaryText: "시급 26,000~36,000",
    workHours: "PM 6:00 ~ AM 2:00",
    benefits: "식사 제공, 의상 제공",
    description: "부산 남포동 텐카페에서 함께할 분을 찾습니다.\n\n관광객 많은 활기찬 곳!",
    contactPhone: "01043219876",
    thumbnailUrl: null,
  },
  {
    title: "대구 중구 레깅스룸 정직원",
    businessName: "중구 비너스",
    businessType: "LEGGINGS_ROOM" as const,
    regions: ["DAEGU" as const],
    salaryText: "일급 29만~44만",
    workHours: "PM 7:00 ~ AM 3:00",
    benefits: "레깅스 제공, 식사, 택시비",
    description: "대구 중구 대형 레깅스룸입니다.\n\n안정적인 수입과 좋은 환경!",
    contactPhone: "01032198765",
    thumbnailUrl: null,
  },
  {
    title: "대전 은행동 셔츠룸 채용",
    businessName: "은행 골든게이트",
    businessType: "SHIRT_ROOM" as const,
    regions: ["DAEJEON" as const],
    salaryText: "일급 30만~45만",
    workHours: "PM 7:30 ~ AM 3:00",
    benefits: "셔츠 제공, 식사, 택시비",
    description: "대전 은행동 중심가 셔츠룸입니다.\n\n깔끔한 시설과 체계적인 관리!",
    contactPhone: "01021987654",
    thumbnailUrl: null,
  },
  {
    title: "광주 충장로 텐카페 모집",
    businessName: "충장 드림카페",
    businessType: "TEN_CAFE" as const,
    regions: ["GWANGJU" as const],
    salaryText: "시급 25,000~35,000",
    workHours: "PM 6:00 ~ AM 2:00",
    benefits: "식사 제공, 의상 제공",
    description: "광주 충장로 중심가 텐카페입니다.\n\n활기차고 밝은 분위기!",
    contactPhone: "01010987654",
    thumbnailUrl: null,
  },
  {
    title: "인천 부평 퍼블릭바 스탭",
    businessName: "부평 나이트온",
    businessType: "PUBLIC_BAR" as const,
    regions: ["INCHEON" as const],
    salaryText: "시급 24,000~34,000+팁",
    workHours: "PM 9:00 ~ AM 5:00",
    benefits: "식사 제공, 팁 전액 본인",
    description: "인천 부평 중심가 퍼블릭바입니다.\n\n손님 많고 팁 좋은 곳!",
    contactPhone: "01019876542",
    thumbnailUrl: null,
  },
  // 49-58. SPECIAL (10개)
  {
    title: "강북 바라운지 스탭 모집",
    businessName: "강북 문라이트",
    businessType: "BAR_LOUNGE" as const,
    regions: ["SEOUL" as const],
    salaryText: "시급 22,000~32,000",
    workHours: "PM 8:00 ~ AM 4:00",
    benefits: "식사 제공, 택시비 지원",
    description: "강북 지역 바라운지에서 스탭을 구합니다.\n\n편안한 분위기!",
    contactPhone: "01098765430",
    thumbnailUrl: null,
  },
  {
    title: "구로 노래방 도우미 채용",
    businessName: "구로 골든노래방",
    businessType: "KARAOKE" as const,
    regions: ["SEOUL" as const],
    salaryText: "일급 18만~28만",
    workHours: "PM 7:00 ~ AM 2:00",
    benefits: "식사 제공, 의상 제공",
    description: "구로디지털단지역 인근 노래방입니다.\n\n편하게 일하실 분!",
    contactPhone: "01087654319",
    thumbnailUrl: null,
  },
  {
    title: "용인 수지 텐카페 모집",
    businessName: "수지 브라운카페",
    businessType: "TEN_CAFE" as const,
    regions: ["GYEONGGI" as const],
    salaryText: "시급 23,000~33,000",
    workHours: "PM 6:00 ~ AM 2:00",
    benefits: "식사 제공, 의상 제공",
    description: "용인 수지 신도시 텐카페입니다.\n\n깔끔한 환경!",
    contactPhone: "01076543218",
    thumbnailUrl: null,
  },
  {
    title: "성남 중원 셔츠룸 스탭",
    businessName: "중원 실버문",
    businessType: "SHIRT_ROOM" as const,
    regions: ["GYEONGGI" as const],
    salaryText: "일급 26만~41만",
    workHours: "PM 7:30 ~ AM 3:00",
    benefits: "셔츠 제공, 식사, 택시비",
    description: "성남 중원구 셔츠룸입니다.\n\n안정적인 수입!",
    contactPhone: "01065432197",
    thumbnailUrl: null,
  },
  {
    title: "부산 광안 클럽 주말 파트",
    businessName: "광안 비트클럽",
    businessType: "CLUB" as const,
    regions: ["BUSAN" as const],
    salaryText: "시급 32,000+팁",
    workHours: "PM 10:00 ~ AM 5:00 (금토)",
    benefits: "팁 전액, 음료 무제한",
    description: "광안리 해변 클럽에서 주말 파트를 구합니다.\n\n관광객 많고 팁 좋음!",
    contactPhone: "01054321986",
    thumbnailUrl: null,
  },
  {
    title: "부산 센텀 바라운지 채용",
    businessName: "센텀 문스카이",
    businessType: "BAR_LOUNGE" as const,
    regions: ["BUSAN" as const],
    salaryText: "시급 21,000~31,000",
    workHours: "PM 8:00 ~ AM 4:00",
    benefits: "식사 제공, 택시비 지원",
    description: "센텀시티 바라운지에서 스탭을 모집합니다.\n\n깨끗한 신축 건물!",
    contactPhone: "01043219875",
    thumbnailUrl: null,
  },
  {
    title: "대구 북구 노래방 도우미",
    businessName: "북구 뮤직노래방",
    businessType: "KARAOKE" as const,
    regions: ["DAEGU" as const],
    salaryText: "일급 17만~27만",
    workHours: "PM 7:00 ~ AM 2:00",
    benefits: "식사 제공, 의상 제공",
    description: "대구 북구 대형 노래방입니다.\n\n편한 분위기!",
    contactPhone: "01032198764",
    thumbnailUrl: null,
  },
  {
    title: "대전 중구 마사지샵 관리사",
    businessName: "중구 로얄스파",
    businessType: "MASSAGE" as const,
    regions: ["DAEJEON" as const],
    salaryText: "월급 260만~360만",
    workHours: "AM 11:00 ~ PM 10:00 (교대)",
    benefits: "숙소 제공, 식사 제공",
    description: "대전 중구 마사지샵입니다.\n\n경력자 우대!",
    contactPhone: "01021987653",
    thumbnailUrl: null,
  },
  {
    title: "광주 서구 퍼블릭바 스탭",
    businessName: "서구 레인보우바",
    businessType: "PUBLIC_BAR" as const,
    regions: ["GWANGJU" as const],
    salaryText: "시급 20,000~30,000+팁",
    workHours: "PM 9:00 ~ AM 5:00",
    benefits: "식사 제공, 팁 전액 본인",
    description: "광주 서구 퍼블릭바입니다.\n\n손님 많고 팁 좋음!",
    contactPhone: "01010987653",
    thumbnailUrl: null,
  },
  {
    title: "제주 신제주 바라운지 채용",
    businessName: "신제주 오렌지라운지",
    businessType: "BAR_LOUNGE" as const,
    regions: ["JEJU" as const],
    salaryText: "시급 23,000~33,000",
    workHours: "PM 7:00 ~ AM 3:00",
    benefits: "숙소 제공, 식사 제공, 항공권 지원",
    description: "제주 신제주 바라운지입니다.\n\n숙소+항공권 지원!",
    contactPhone: "01019876541",
    thumbnailUrl: null,
  },
  // 59-68. URGENT (10개)
  {
    title: "강남 셔츠룸 급구",
    businessName: "강남 스피드",
    businessType: "SHIRT_ROOM" as const,
    regions: ["SEOUL" as const],
    salaryText: "일급 30만~48만",
    workHours: "PM 7:30 ~ AM 3:00",
    benefits: "셔츠 제공, 식사, 택시비, 당일정산",
    description: "강남역 셔츠룸 긴급 채용!\n\n바로 출근 가능하신 분. 당일정산!",
    contactPhone: "01098765429",
    thumbnailUrl: null,
  },
  {
    title: "신논현 하이퍼블릭 긴급 모집",
    businessName: "신논현 파이어",
    businessType: "HYPER_PUBLIC" as const,
    regions: ["SEOUL" as const],
    salaryText: "일급 28만~46만+팁",
    workHours: "PM 8:00 ~ AM 5:00",
    benefits: "의상, 식사, 택시비, 당일정산",
    description: "신논현 하이퍼블릭 급구!\n\n오늘 출근 가능하신 분 우대!",
    contactPhone: "01087654318",
    thumbnailUrl: null,
  },
  {
    title: "서초 바라운지 오늘 출근 가능자",
    businessName: "서초 썬더라운지",
    businessType: "BAR_LOUNGE" as const,
    regions: ["SEOUL" as const],
    salaryText: "시급 24,000~34,000",
    workHours: "PM 8:00 ~ AM 4:00",
    benefits: "식사 제공, 택시비, 당일정산",
    description: "서초동 바라운지 긴급 채용!\n\n오늘 출근 가능자만 연락주세요!",
    contactPhone: "01076543217",
    contactKakao: "thunder_sc",
    thumbnailUrl: null,
  },
  {
    title: "분당 텐카페 급구",
    businessName: "분당 스피드카페",
    businessType: "TEN_CAFE" as const,
    regions: ["GYEONGGI" as const],
    salaryText: "시급 27,000~37,000",
    workHours: "PM 6:00 ~ AM 2:00",
    benefits: "식사, 의상, 택시비, 당일정산",
    description: "분당 텐카페 긴급 모집!\n\n바로 출근 가능하신 분!",
    contactPhone: "01065432196",
    thumbnailUrl: null,
  },
  {
    title: "평택 셔츠룸 긴급 채용",
    businessName: "평택 플래시",
    businessType: "SHIRT_ROOM" as const,
    regions: ["GYEONGGI" as const],
    salaryText: "일급 27만~44만",
    workHours: "PM 7:30 ~ AM 3:00",
    benefits: "셔츠, 식사, 택시비, 당일정산",
    description: "평택역 앞 셔츠룸 급구!\n\n당일 출근 가능자 우대!",
    contactPhone: "01054321985",
    thumbnailUrl: null,
  },
  {
    title: "부산 서면 퍼블릭 급구",
    businessName: "서면 라이트닝",
    businessType: "PUBLIC_BAR" as const,
    regions: ["BUSAN" as const],
    salaryText: "시급 23,000+팁",
    workHours: "PM 9:00 ~ AM 5:00",
    benefits: "식사, 팁 전액, 당일정산",
    description: "서면 퍼블릭바 긴급 채용!\n\n오늘 출근 가능자!",
    contactPhone: "01043219874",
    thumbnailUrl: null,
  },
  {
    title: "부산 동래 노래방 급구",
    businessName: "동래 뮤직홀",
    businessType: "KARAOKE" as const,
    regions: ["BUSAN" as const],
    salaryText: "일급 16만~26만",
    workHours: "PM 7:00 ~ AM 2:00",
    benefits: "식사, 의상, 당일정산",
    description: "부산 동래 노래방 긴급 모집!\n\n바로 출근 가능자!",
    contactPhone: "01032198763",
    thumbnailUrl: null,
  },
  {
    title: "대구 동성로 클럽 주말 급구",
    businessName: "동성 펄스클럽",
    businessType: "CLUB" as const,
    regions: ["DAEGU" as const],
    salaryText: "시급 33,000+팁",
    workHours: "PM 10:00 ~ AM 5:00 (금토)",
    benefits: "팁 전액, 음료, 당일정산",
    description: "대구 동성로 클럽 주말 급구!\n\n이번주 출근 가능자!",
    contactPhone: "01021987652",
    thumbnailUrl: null,
  },
  {
    title: "대전 둔산 바라운지 오늘 출근",
    businessName: "둔산 스타라운지",
    businessType: "BAR_LOUNGE" as const,
    regions: ["DAEJEON" as const],
    salaryText: "시급 22,000~32,000",
    workHours: "PM 8:00 ~ AM 4:00",
    benefits: "식사, 택시비, 당일정산",
    description: "대전 둔산 바라운지 긴급!\n\n오늘 출근 가능하신 분만!",
    contactPhone: "01010987652",
    thumbnailUrl: null,
  },
  {
    title: "인천 구월 셔츠룸 급구",
    businessName: "구월 블리츠",
    businessType: "SHIRT_ROOM" as const,
    regions: ["INCHEON" as const],
    salaryText: "일급 28만~45만",
    workHours: "PM 7:30 ~ AM 3:00",
    benefits: "셔츠, 식사, 택시비, 당일정산",
    description: "인천 구월동 셔츠룸 급구!\n\n바로 출근 가능자 연락주세요!",
    contactPhone: "01019876540",
    thumbnailUrl: null,
  },
  // 69-78. RECOMMEND (10개)
  {
    title: "망원 노래방 도우미 모집",
    businessName: "망원 멜로디",
    businessType: "KARAOKE" as const,
    regions: ["SEOUL" as const],
    salaryText: "일급 16만~26만",
    workHours: "PM 7:00 ~ AM 2:00",
    benefits: "식사, 의상 제공",
    description: "망원동 노래방에서 도우미를 구합니다.\n\n편한 분위기!",
    contactPhone: "01098765428",
    thumbnailUrl: null,
  },
  {
    title: "연남 텐카페 스탭",
    businessName: "연남 그린카페",
    businessType: "TEN_CAFE" as const,
    regions: ["SEOUL" as const],
    salaryText: "시급 21,000~31,000",
    workHours: "PM 6:00 ~ AM 2:00",
    benefits: "식사, 의상 제공",
    description: "연남동 텐카페입니다.\n\n힙한 동네에서 일하기!",
    contactPhone: "01087654317",
    thumbnailUrl: null,
  },
  {
    title: "안산 하이퍼블릭 정직원",
    businessName: "안산 팡팡클럽",
    businessType: "HYPER_PUBLIC" as const,
    regions: ["GYEONGGI" as const],
    salaryText: "일급 24만~39만",
    workHours: "PM 8:00 ~ AM 4:00",
    benefits: "숙소, 식사, 의상, 택시비",
    description: "안산 다문화특구 하이퍼블릭입니다.\n\n외국인 손님 많음!",
    contactPhone: "01076543216",
    thumbnailUrl: null,
  },
  {
    title: "화성 동탄 관리실 관리사",
    businessName: "동탄 힐링타임",
    businessType: "GUANRI" as const,
    regions: ["GYEONGGI" as const],
    salaryText: "월급 270만~370만",
    workHours: "AM 11:00 ~ PM 10:00 (교대)",
    benefits: "숙소, 식사, 4대보험",
    description: "동탄 신도시 관리실입니다.\n\n깔끔한 시설!",
    contactPhone: "01065432195",
    thumbnailUrl: null,
  },
  {
    title: "부천 중동 퍼블릭바 스탭",
    businessName: "중동 썬바",
    businessType: "PUBLIC_BAR" as const,
    regions: ["GYEONGGI" as const],
    salaryText: "시급 21,000~31,000+팁",
    workHours: "PM 9:00 ~ AM 5:00",
    benefits: "식사, 팁 전액",
    description: "부천 중동 퍼블릭바입니다.\n\n손님 많음!",
    contactPhone: "01054321984",
    thumbnailUrl: null,
  },
  {
    title: "창원 성산 바라운지 채용",
    businessName: "성산 선라이즈",
    businessType: "BAR_LOUNGE" as const,
    regions: ["GYEONGNAM" as const],
    salaryText: "시급 20,000~30,000",
    workHours: "PM 8:00 ~ AM 4:00",
    benefits: "식사, 택시비",
    description: "창원 성산구 바라운지입니다.\n\n경남 최대 도시!",
    contactPhone: "01043219873",
    thumbnailUrl: null,
  },
  {
    title: "천안 신부 노래방 도우미",
    businessName: "신부 뮤직타운",
    businessType: "KARAOKE" as const,
    regions: ["CHUNGNAM" as const],
    salaryText: "일급 15만~25만",
    workHours: "PM 7:00 ~ AM 2:00",
    benefits: "식사, 의상",
    description: "천안 신부동 노래방입니다.\n\n교통 편리!",
    contactPhone: "01032198762",
    thumbnailUrl: null,
  },
  {
    title: "전주 효자 마사지샵 관리사",
    businessName: "효자 로얄마사지",
    businessType: "MASSAGE" as const,
    regions: ["JEONBUK" as const],
    salaryText: "월급 255만~355만",
    workHours: "AM 11:00 ~ PM 10:00 (교대)",
    benefits: "숙소, 식사",
    description: "전주 효자동 마사지샵입니다.\n\n신입도 환영!",
    contactPhone: "01021987651",
    thumbnailUrl: null,
  },
  {
    title: "원주 중앙 텐카페 모집",
    businessName: "원주 블루카페",
    businessType: "TEN_CAFE" as const,
    regions: ["GANGWON" as const],
    salaryText: "시급 20,000~30,000",
    workHours: "PM 6:00 ~ AM 2:00",
    benefits: "식사, 의상",
    description: "원주 중앙동 텐카페입니다.\n\n강원권 손님 많음!",
    contactPhone: "01010987651",
    thumbnailUrl: null,
  },
  {
    title: "포항 북구 퍼블릭바 스탭",
    businessName: "북구 오션바",
    businessType: "PUBLIC_BAR" as const,
    regions: ["GYEONGBUK" as const],
    salaryText: "시급 19,000~29,000+팁",
    workHours: "PM 9:00 ~ AM 5:00",
    benefits: "식사, 팁 전액",
    description: "포항 북구 퍼블릭바입니다.\n\n제철소 근처!",
    contactPhone: "01019876539",
    thumbnailUrl: null,
  },
  // 79-88. LINE (10개)
  {
    title: "마포 클럽 주말 알바",
    businessName: "마포 비트박스",
    businessType: "CLUB" as const,
    regions: ["SEOUL" as const],
    salaryText: "시급 29,000+팁",
    workHours: "PM 10:00 ~ AM 5:00 (금토)",
    benefits: "팁 전액, 음료",
    description: "마포 클럽 주말 파트입니다.\n\n젊은 손님 많음!",
    contactPhone: "01098765427",
    thumbnailUrl: null,
  },
  {
    title: "양천 노래방 파트타임",
    businessName: "양천 뮤직파크",
    businessType: "KARAOKE" as const,
    regions: ["SEOUL" as const],
    salaryText: "시급 17,000~24,000",
    workHours: "PM 8:00 ~ AM 2:00",
    benefits: "식사",
    description: "양천구 노래방 파트입니다.\n\n주말만 가능!",
    contactPhone: "01087654316",
    thumbnailUrl: null,
  },
  {
    title: "고양 일산 바 스탭",
    businessName: "일산 나이트바",
    businessType: "PUBLIC_BAR" as const,
    regions: ["GYEONGGI" as const],
    salaryText: "시급 20,000~28,000+팁",
    workHours: "PM 9:00 ~ AM 5:00",
    benefits: "식사, 팁 전액",
    description: "고양 일산 바입니다.\n\n신도시 깔끔!",
    contactPhone: "01076543215",
    thumbnailUrl: null,
  },
  {
    title: "광명 마사지샵 관리사",
    businessName: "광명 힐링센터",
    businessType: "MASSAGE" as const,
    regions: ["GYEONGGI" as const],
    salaryText: "월급 240만~340만",
    workHours: "AM 11:00 ~ PM 10:00 (교대)",
    benefits: "숙소, 식사",
    description: "광명 중심가 마사지샵입니다.\n\n경력자 우대!",
    contactPhone: "01065432194",
    thumbnailUrl: null,
  },
  {
    title: "의정부 노래방 도우미",
    businessName: "의정부 뮤직홀",
    businessType: "KARAOKE" as const,
    regions: ["GYEONGGI" as const],
    salaryText: "일급 14만~23만",
    workHours: "PM 7:00 ~ AM 2:00",
    benefits: "식사",
    description: "의정부 중심가 노래방입니다.\n\n미군 손님 많음!",
    contactPhone: "01054321983",
    thumbnailUrl: null,
  },
  {
    title: "진해 바라운지 스탭",
    businessName: "진해 바다라운지",
    businessType: "BAR_LOUNGE" as const,
    regions: ["GYEONGNAM" as const],
    salaryText: "시급 19,000~27,000",
    workHours: "PM 7:00 ~ AM 3:00",
    benefits: "식사, 택시비",
    description: "진해 바라운지입니다.\n\n해변 근처!",
    contactPhone: "01043219872",
    thumbnailUrl: null,
  },
  {
    title: "목포 클럽 주말 파트",
    businessName: "목포 웨이브클럽",
    businessType: "CLUB" as const,
    regions: ["JEONNAM" as const],
    salaryText: "시급 28,000+팁",
    workHours: "PM 10:00 ~ AM 5:00 (금토)",
    benefits: "팁 전액, 음료",
    description: "목포 클럽 주말 알바입니다.\n\n항구도시 분위기!",
    contactPhone: "01032198761",
    thumbnailUrl: null,
  },
  {
    title: "여수 노래방 도우미",
    businessName: "여수 뮤직바다",
    businessType: "KARAOKE" as const,
    regions: ["JEONNAM" as const],
    salaryText: "일급 14만~22만",
    workHours: "PM 8:00 ~ AM 2:00",
    benefits: "식사",
    description: "여수 중심가 노래방입니다.\n\n관광객 많음!",
    contactPhone: "01021987650",
    thumbnailUrl: null,
  },
  {
    title: "속초 바라운지 채용",
    businessName: "속초 설악라운지",
    businessType: "BAR_LOUNGE" as const,
    regions: ["GANGWON" as const],
    salaryText: "시급 18,000~26,000",
    workHours: "PM 7:00 ~ AM 3:00",
    benefits: "숙소, 식사",
    description: "속초 해변 바라운지입니다.\n\n여름 시즌 보너스!",
    contactPhone: "01010987650",
    thumbnailUrl: null,
  },
  {
    title: "제천 마사지샵 관리사",
    businessName: "제천 힐링스파",
    businessType: "MASSAGE" as const,
    regions: ["CHUNGBUK" as const],
    salaryText: "월급 235만~335만",
    workHours: "AM 11:00 ~ PM 10:00 (교대)",
    benefits: "숙소, 식사",
    description: "제천 중심가 마사지샵입니다.\n\n신입 환영!",
    contactPhone: "01019876538",
    thumbnailUrl: null,
  },
  // 89-98. FREE (10개)
  {
    title: "성북 카페 아르바이트",
    businessName: "성북 데이카페",
    businessType: "TEN_CAFE" as const,
    regions: ["SEOUL" as const],
    salaryText: "시급 14,000",
    workHours: "PM 2:00 ~ PM 10:00",
    benefits: "식사",
    description: "성북구 카페 알바입니다.\n\n주말 가능자!",
    contactPhone: "01098765426",
    thumbnailUrl: null,
  },
  {
    title: "은평 노래방 주말 알바",
    businessName: "은평 노래마을",
    businessType: "KARAOKE" as const,
    regions: ["SEOUL" as const],
    salaryText: "일급 11만~17만",
    workHours: "PM 8:00 ~ AM 2:00 (주말)",
    benefits: "식사",
    description: "은평구 노래방 주말 알바입니다.\n\n편한 분위기!",
    contactPhone: "01087654315",
    thumbnailUrl: null,
  },
  {
    title: "남양주 술집 홀 서빙",
    businessName: "남양주 전통주막",
    businessType: "PUBLIC_BAR" as const,
    regions: ["GYEONGGI" as const],
    salaryText: "시급 11,000",
    workHours: "PM 6:00 ~ AM 1:00",
    benefits: "식사",
    description: "남양주 술집 홀 서빙입니다.\n\n초보 환영!",
    contactPhone: "01076543214",
    thumbnailUrl: null,
  },
  {
    title: "파주 카페 파트타임",
    businessName: "파주 힐링카페",
    businessType: "TEN_CAFE" as const,
    regions: ["GYEONGGI" as const],
    salaryText: "시급 13,000",
    workHours: "PM 3:00 ~ PM 11:00",
    benefits: "식사",
    description: "파주 카페 파트입니다.\n\n평일 가능자!",
    contactPhone: "01065432193",
    thumbnailUrl: null,
  },
  {
    title: "김포 노래방 도우미",
    businessName: "김포 뮤직홀",
    businessType: "KARAOKE" as const,
    regions: ["GYEONGGI" as const],
    salaryText: "일급 10만~16만",
    workHours: "PM 8:00 ~ AM 2:00",
    benefits: "식사",
    description: "김포 노래방입니다.\n\n공항 근처!",
    contactPhone: "01054321982",
    thumbnailUrl: null,
  },
  {
    title: "양산 술집 홀 스탭",
    businessName: "양산 오래된집",
    businessType: "PUBLIC_BAR" as const,
    regions: ["GYEONGNAM" as const],
    salaryText: "시급 10,500",
    workHours: "PM 6:00 ~ AM 1:00",
    benefits: "식사",
    description: "양산 술집 홀 서빙입니다.\n\n부산 인접!",
    contactPhone: "01043219871",
    thumbnailUrl: null,
  },
  {
    title: "청주 흥덕 카페 알바",
    businessName: "흥덕 브릭카페",
    businessType: "TEN_CAFE" as const,
    regions: ["CHUNGBUK" as const],
    salaryText: "시급 12,500",
    workHours: "PM 2:00 ~ PM 10:00",
    benefits: "식사",
    description: "청주 흥덕구 카페입니다.\n\n대학가!",
    contactPhone: "01032198760",
    thumbnailUrl: null,
  },
  {
    title: "공주 노래방 주말 알바",
    businessName: "공주 뮤직타운",
    businessType: "KARAOKE" as const,
    regions: ["CHUNGNAM" as const],
    salaryText: "일급 10만~15만",
    workHours: "PM 8:00 ~ AM 2:00 (주말)",
    benefits: "식사",
    description: "공주 노래방 주말 알바입니다.\n\n대학생 환영!",
    contactPhone: "01021987649",
    thumbnailUrl: null,
  },
  {
    title: "익산 술집 홀 서빙",
    businessName: "익산 보리술집",
    businessType: "PUBLIC_BAR" as const,
    regions: ["JEONBUK" as const],
    salaryText: "시급 11,500",
    workHours: "PM 6:00 ~ AM 1:00",
    benefits: "식사",
    description: "익산 술집 서빙입니다.\n\n편한 분위기!",
    contactPhone: "01010987649",
    thumbnailUrl: null,
  },
  {
    title: "삼척 카페 아르바이트",
    businessName: "삼척 바다카페",
    businessType: "TEN_CAFE" as const,
    regions: ["GANGWON" as const],
    salaryText: "시급 13,500",
    workHours: "PM 2:00 ~ PM 10:00",
    benefits: "식사",
    description: "삼척 해변 카페입니다.\n\n바다 전망!",
    contactPhone: "01019876537",
    thumbnailUrl: null,
  },
];

async function main() {
  console.log("Seeding database...");

  // 기존 데이터 삭제
  await prisma.jumpLog.deleteMany();
  await prisma.adOption.deleteMany();
  await prisma.adDailyMetric.deleteMany();
  await prisma.scrap.deleteMany();
  await prisma.review.deleteMany();
  await prisma.payment.deleteMany();
  await prisma.ad.deleteMany();
  await prisma.resume.deleteMany();
  await prisma.notification.deleteMany();
  await prisma.session.deleteMany();
  await prisma.account.deleteMany();
  await prisma.user.deleteMany();

  // 사장님 계정 생성
  const bizPassword = await hash("test1234", 12);
  const bizUser = await prisma.user.create({
    data: {
      name: "테스트사장",
      email: "boss@yeosialba.com",
      phone: "01099998888",
      hashedPassword: bizPassword,
      role: "BUSINESS",
      businessName: "테스트업소",
      isVerifiedBiz: true,
    },
  });

  // 구직자 계정 생성
  const jobPassword = await hash("test1234", 12);
  await prisma.user.create({
    data: {
      name: "테스트구직자",
      email: "job@yeosialba.com",
      phone: "01077776666",
      hashedPassword: jobPassword,
      role: "JOBSEEKER",
    },
  });

  // 관리자 계정 생성
  const adminPassword = await hash("admin1234", 12);
  await prisma.user.create({
    data: {
      name: "관리자",
      email: "admin@yeosialba.com",
      phone: "01000000000",
      hashedPassword: adminPassword,
      role: "ADMIN",
    },
  });

  // 광고 생성
  const now = new Date();
  for (let i = 0; i < SAMPLE_ADS.length; i++) {
    const sample = SAMPLE_ADS[i];
    const startDate = new Date(now);
    startDate.setDate(startDate.getDate() - Math.floor(Math.random() * 10));
    const endDate = new Date(startDate);
    endDate.setDate(endDate.getDate() + 30);

    const lastJumped = new Date(now);
    lastJumped.setMinutes(lastJumped.getMinutes() - i * 15);

    // 등급별 차별화: BANNER 11, VIP 12, PREMIUM 12, SPECIAL 12, URGENT 12, RECOMMEND 12, LINE 14, FREE 13 (총 98개)
    const productIds = [
      // 기존 18개
      "BANNER", "VIP", "VIP", "PREMIUM", "PREMIUM", "SPECIAL", "SPECIAL", "URGENT", "URGENT", "RECOMMEND", "RECOMMEND", "LINE", "LINE", "LINE", "LINE", "FREE", "FREE", "FREE",
      // 추가 80개: 각 등급별 10개씩
      // BANNER 10개 (19-28)
      "BANNER", "BANNER", "BANNER", "BANNER", "BANNER", "BANNER", "BANNER", "BANNER", "BANNER", "BANNER",
      // VIP 10개 (29-38)
      "VIP", "VIP", "VIP", "VIP", "VIP", "VIP", "VIP", "VIP", "VIP", "VIP",
      // PREMIUM 10개 (39-48)
      "PREMIUM", "PREMIUM", "PREMIUM", "PREMIUM", "PREMIUM", "PREMIUM", "PREMIUM", "PREMIUM", "PREMIUM", "PREMIUM",
      // SPECIAL 10개 (49-58)
      "SPECIAL", "SPECIAL", "SPECIAL", "SPECIAL", "SPECIAL", "SPECIAL", "SPECIAL", "SPECIAL", "SPECIAL", "SPECIAL",
      // URGENT 10개 (59-68)
      "URGENT", "URGENT", "URGENT", "URGENT", "URGENT", "URGENT", "URGENT", "URGENT", "URGENT", "URGENT",
      // RECOMMEND 10개 (69-78)
      "RECOMMEND", "RECOMMEND", "RECOMMEND", "RECOMMEND", "RECOMMEND", "RECOMMEND", "RECOMMEND", "RECOMMEND", "RECOMMEND", "RECOMMEND",
      // LINE 10개 (79-88)
      "LINE", "LINE", "LINE", "LINE", "LINE", "LINE", "LINE", "LINE", "LINE", "LINE",
      // FREE 10개 (89-98)
      "FREE", "FREE", "FREE", "FREE", "FREE", "FREE", "FREE", "FREE", "FREE", "FREE"
    ] as const;
    const amounts = [
      // 기존 18개
      700000, 500000, 500000, 300000, 300000, 200000, 200000, 150000, 150000, 100000, 100000, 70000, 70000, 70000, 70000, 0, 0, 0,
      // 추가 80개
      // BANNER 10개 (700000)
      700000, 700000, 700000, 700000, 700000, 700000, 700000, 700000, 700000, 700000,
      // VIP 10개 (500000)
      500000, 500000, 500000, 500000, 500000, 500000, 500000, 500000, 500000, 500000,
      // PREMIUM 10개 (300000)
      300000, 300000, 300000, 300000, 300000, 300000, 300000, 300000, 300000, 300000,
      // SPECIAL 10개 (200000)
      200000, 200000, 200000, 200000, 200000, 200000, 200000, 200000, 200000, 200000,
      // URGENT 10개 (150000)
      150000, 150000, 150000, 150000, 150000, 150000, 150000, 150000, 150000, 150000,
      // RECOMMEND 10개 (100000)
      100000, 100000, 100000, 100000, 100000, 100000, 100000, 100000, 100000, 100000,
      // LINE 10개 (70000)
      70000, 70000, 70000, 70000, 70000, 70000, 70000, 70000, 70000, 70000,
      // FREE 10개 (0)
      0, 0, 0, 0, 0, 0, 0, 0, 0, 0
    ];
    const isFreeAd = productIds[i] === "FREE";

    await prisma.ad.create({
      data: {
        userId: bizUser.id,
        title: sample.title,
        businessName: sample.businessName,
        businessType: sample.businessType,
        regions: sample.regions,
        salaryText: sample.salaryText,
        workHours: sample.workHours || null,
        benefits: sample.benefits || null,
        description: sample.description,
        contactPhone: sample.contactPhone,
        contactKakao: sample.contactKakao || null,
        productId: productIds[i],
        durationDays: isFreeAd ? 0 : 30,
        totalAmount: amounts[i],
        status: "ACTIVE",
        startDate: isFreeAd ? new Date() : startDate,
        endDate: isFreeAd ? undefined : endDate,
        autoJumpPerDay: isFreeAd ? 0 : 12,
        manualJumpPerDay: 0,
        lastJumpedAt: lastJumped,
        isVerified: i < 5,
        viewCount: Math.floor(Math.random() * 500),
        maxEdits: isFreeAd ? 999 : 1,
      },
    });
  }

  // 구직자 이력서 생성
  const jobUser = await prisma.user.findUnique({ where: { email: "job@yeosialba.com" } });

  // 추가 구직자 계정 + 이력서 생성
  const jobPassword2 = await hash("test1234", 12);
  const jobUser2 = await prisma.user.create({
    data: {
      name: "김서연",
      email: "job2@yeosialba.com",
      phone: "01055554444",
      hashedPassword: jobPassword2,
      role: "JOBSEEKER",
    },
  });
  const jobUser3 = await prisma.user.create({
    data: {
      name: "이유진",
      email: "job3@yeosialba.com",
      phone: "01033332222",
      hashedPassword: jobPassword2,
      role: "JOBSEEKER",
    },
  });

  if (jobUser) {
    await prisma.resume.create({
      data: {
        userId: jobUser.id,
        nickname: "밝은미소",
        gender: "여성",
        age: 25,
        height: 165,
        weight: 50,
        region: "SEOUL",
        districts: ["서울 강남구", "서울 서초구"],
        desiredJobs: ["ROOM_SALON", "KARAOKE"],
        experienceLevel: "UNDER_6M",
        desiredSalaryType: "DAILY",
        desiredSalaryAmount: 200000,
        availableHours: "오후 7시~새벽 2시",
        kakaoId: "bright_smile",
        phone: "010-7777-6666",
        title: "성실하게 일하겠습니다",
        introduction: "안녕하세요. 밝은 성격의 25세 여성입니다. 경험은 적지만 항상 밝은 미소로 열심히 하겠습니다. 강남/서초 지역에서 근무를 희망합니다.",
        isPublic: true,
        lastBumpedAt: now,
      },
    });
  }

  await prisma.resume.create({
    data: {
      userId: jobUser2.id,
      nickname: "예쁜언니",
      gender: "여성",
      age: 28,
      height: 170,
      weight: 52,
      region: "SEOUL",
      districts: ["서울 마포구", "서울 영등포구"],
      desiredJobs: ["TEN_CAFE", "BAR_LOUNGE", "PUBLIC_BAR"],
      experienceLevel: "1Y_TO_3Y",
      desiredSalaryType: "DAILY",
      desiredSalaryAmount: 300000,
      availableHours: "평일 오후 8시~새벽 3시",
      kakaoId: "pretty_unni28",
      title: "경력 2년차 프로입니다",
      introduction: "텐카페, 바라운지 경력 2년입니다. 서비스 마인드가 좋다는 평가를 많이 받았습니다. 마포/영등포 지역 희망합니다.",
      isPublic: true,
      lastBumpedAt: new Date(now.getTime() - 2 * 60 * 60 * 1000),
    },
  });

  await prisma.resume.create({
    data: {
      userId: jobUser3.id,
      nickname: "새출발",
      gender: "여성",
      age: 22,
      region: "BUSAN",
      districts: ["부산 해운대구"],
      desiredJobs: ["KARAOKE", "CLUB"],
      experienceLevel: "BEGINNER",
      desiredSalaryType: "NEGOTIABLE",
      availableHours: "주말 가능",
      kakaoId: "new_start22",
      phone: "010-3333-2222",
      title: "초보지만 열심히 하겠습니다",
      introduction: "안녕하세요! 부산 해운대 거주 22세입니다. 처음이라 긴장되지만 열심히 배우겠습니다.",
      isPublic: true,
      lastBumpedAt: new Date(now.getTime() - 24 * 60 * 60 * 1000),
    },
  });

  // 공지사항 시드
  const adminUser = await prisma.user.findUnique({ where: { email: "admin@yeosialba.com" } });
  if (adminUser) {
    await prisma.notice.deleteMany();
    const notices = [
      {
        title: "여시잡 오픈 안내",
        content: "안녕하세요, 여시잡입니다.\n\n밤여시 카페 기반의 신뢰할 수 있는 구인구직 플랫폼 '여시잡'이 오픈했습니다.\n\n사장님은 합리적인 가격에 구인 광고를, 구직자는 믿을 수 있는 채용정보를 만나보세요.\n\n많은 이용 부탁드립니다. 감사합니다.",
        isPinned: true,
        viewCount: 156,
      },
      {
        title: "광고 등록 가이드",
        content: "광고 등록 방법을 안내합니다.\n\n1. 사장님 회원가입 후 로그인\n2. 상단 '광고등록' 버튼 클릭\n3. 업소 정보 입력 (업소명, 업종, 연락처, 근무조건 등)\n4. 광고 등급 선택 (무료~특수배너)\n5. 결제 후 광고 게시\n\n무료 등급도 있으니 부담 없이 시작하세요!\n문의사항은 고객센터로 연락 주세요.",
        isPinned: true,
        viewCount: 89,
      },
      {
        title: "이용약관 안내",
        content: "여시잡 이용약관을 안내합니다.\n\n1. 서비스 이용 시 허위 정보 기재를 금지합니다.\n2. 타인의 개인정보를 무단으로 수집/이용하는 행위를 금지합니다.\n3. 불법적인 업소 광고는 즉시 삭제되며, 계정이 정지될 수 있습니다.\n4. 구직자와 사장님 모두 상호 존중하며 건전한 거래 환경을 만들어 주세요.\n\n자세한 내용은 고객센터로 문의 주세요.",
        isPinned: false,
        viewCount: 42,
      },
    ];
    for (const notice of notices) {
      await prisma.notice.create({
        data: {
          ...notice,
          authorId: adminUser.id,
        },
      });
    }
  }

  console.log("Seed complete!");
  console.log("  - 1 Business user: boss@yeosialba.com / test1234");
  console.log("  - 3 Jobseeker users: job@, job2@, job3@yeosialba.com / test1234");
  console.log("  - 1 Admin user: admin@yeosialba.com / admin1234");
  console.log(`  - ${SAMPLE_ADS.length} sample ads (BANNER:11, VIP:12, PREMIUM:12, SPECIAL:12, URGENT:12, RECOMMEND:12, LINE:14, FREE:13)`);
  console.log("  - 3 sample resumes");
  console.log("  - 3 sample notices");
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(() => pool.end());
